## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#ansible-collections-community-vmware-vmware-guest-module

---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
    - name: Create k8s node VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"  # 20.20.20.20
        username: "{{ vcenter_username }}"  # administrator@vsphere.local
        password: "{{ vcenter_password }}"  # VMware1!
        validate_certs: 'false'
        datacenter: '{{datacenter_name}}'   # KH
        name: "k8s-master"
        state: poweredoff
        guest_id: ubuntu64Guest
        esxi_hostname: "{{ esxi_hostname }}"  # phx-esxi-01.vclass.local
        hardware:
          num_cpus: 2
          memory_mb: 4096
        disk:
        - size_gb: 16
          type: thin
          datastore: 'iSCSI-0'       
        networks:
        - name: 'DPG-Prod'
          device_type: vmxnet3
        cdrom:
        - controller_number: 0
          unit_number: 0
          state: present
          type: iso
          #iso_path: '{{ "[" + datastore_name + "]\ISO\TrueNAS-13.0-U4.iso" }}'
      delegate_to: localhost
      register: deploy_vm

