## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_guest_module.html#parameter-customization/joindomain
## https://docs.ansible.com/ansible/latest/collections/community/vmware/docsite/vmware_scenarios/scenario_clone_template.html
## timezone index values - https://learn.microsoft.com/en-us/previous-versions/windows/embedded/ms912391(v=winembedded.11)

---
- hosts: localhost
  vars_files: ./vars.yaml

  tasks: 
    - name: Clone a virtual machine from Windows template and customize
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"  # 200.200.200.251
        username: "{{ vcenter_username }}"  # S00@vclass.local
        password: "{{ vcenter_password }}"  # VMware1!
        datacenter: "{{ datacenter_name }}"
        datastore: "{{ datastore_name }}"
        folder: '{{ folder_prefix + student_ID }}'
        template: "{{ student_ID + '-Win2022-Template'}}"
        name: "{{ student_ID + '-test-DC' }}"
        state: poweredon
        esxi_hostname: "{{ esxi_hostname }}"  # 200.200.200.246
        networks:
        - name: "{{ student_ID + '-Mgmt' }}"  # PHX-Mgmt 포트 그룹에 연결
          ip: 20.20.20.3
          netmask: 255.255.255.0
          gateway: 20.20.20.1
          device_type: vmxnet3
        customization:
          autologon: true
          hostname: 'DC'
          password: 'VMware1!'
          timezone: 230
          joinworkgroup: 'WORKGROUP'
      delegate_to: localhost

