## https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_content_library_manager_module.html#ansible-collections-community-vmware-vmware-content-library-manager-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks: 
    - name: Create Local Content Library
      community.vmware.vmware_content_library_manager:
        hostname: '{{ vcenter_hostname }}'  # 200.200.200.251
        username: '{{ vcenter_username }}'  # S00@vclass.local
        password: '{{ vcenter_password }}'  # VMware1!
        library_name: "{{ student_ID + '-Contents' }}"
        library_type: local
        datastore_name: "iSCSI-0"
        state: present
      delegate_to: localhost
