# https://docs.ansible.com/ansible/latest/collections/community/vmware/vmware_cluster_ha_module.html#ansible-collections-community-vmware-vmware-cluster-ha-module

---
- hosts: localhost
  vars_files: ./vars.yml

  tasks:
    - name: Enable HA
      community.vmware.vmware_cluster_ha:
        hostname: '{{ my_vcenter_hostname }}'
        username: '{{ my_vcenter_username }}'
        password: '{{ my_vcenter_password }}'
        validate_certs: no
        datacenter: '{{ my_datacenter_name }}'
        cluster_name: '{{ my_cluster_name }}'
        enable: true
        apd_response: restartConservative
        pdl_response: restartAggressive
      delegate_to: localhost
